//! Short, action-oriented UI copy. Each key has all four supported translations.
use crate::domain::{bindings::ButtonAction, i18n::Language, models::ControlMode};
macro_rules! catalog {
    ($($key:ident => [$zh:literal, $en:literal, $ja:literal, $ko:literal]),* $(,)?) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum Text { $($key),* }
        impl Text {
            pub fn get(self, language: Language) -> &'static str {
                let labels = match self { $(Self::$key => [$zh, $en, $ja, $ko]),* };
                labels[match language.resolve() { Language::SimplifiedChinese => 0, Language::Japanese => 2, Language::Korean => 3, _ => 1 }]
            }
        }
    };
}
catalog! {
    NoticeInfo => ["状态", "Status", "状態", "상태"],
    NoticeError => ["操作未完成", "Operation failed", "操作が失敗しました", "작업 실패"],
    NoticeWarning => ["需要留意", "Attention needed", "確認が必要です", "확인 필요"],
    OperationWarning => ["部分功能需要检查。查看详情了解原因。", "Some features need attention. View details for the cause.", "一部の機能を確認してください。詳細で原因を確認できます。", "일부 기능을 확인하세요. 자세한 내용에서 원인을 확인할 수 있습니다."],
    ViewDetails => ["查看详情", "View details", "詳細を見る", "자세히 보기"],
    ConnectionFailed => ["连接未完成", "Connection failed", "接続が失敗しました", "연결 실패"],
    DeviceUnreachable => ["无法与设备通信。唤醒控制器并靠近电脑，重新搜索后再连接。仍失败时，检查 Windows 蓝牙状态。", "Cannot reach the device. Wake the controller and move it near the PC. Search again, then connect. If it still fails, check Windows Bluetooth.", "デバイスと通信できません。コントローラーを起こして PC に近づけ、再検索して接続してください。失敗が続く場合は Windows の Bluetooth を確認してください。", "장치와 통신할 수 없습니다. 컨트롤러를 깨우고 PC 가까이에서 다시 검색한 후 연결하세요. 계속 실패하면 Windows Bluetooth를 확인하세요."],
    ConnectionDenied => ["Windows 未允许访问设备。检查蓝牙权限，并确认系统提示后再连接。", "Windows did not allow device access. Check Bluetooth permissions and respond to any system prompt, then connect again.", "Windows がアクセスを許可しませんでした。Bluetooth の権限とシステムの確認画面を確認して再接続してください。", "Windows가 장치 접근을 허용하지 않았습니다. Bluetooth 권한과 시스템 요청을 확인한 후 다시 연결하세요."],
    ConnectionProtocol => ["设备返回通信协议错误。重启控制器后再连接；仍失败时，查看详情。", "The device returned a protocol error. Restart the controller, then connect again. If it still fails, view details.", "通信プロトコルのエラーです。コントローラーを再起動して接続してください。続く場合は詳細を確認してください。", "통신 프로토콜 오류입니다. 컨트롤러를 다시 시작한 후 연결하세요. 계속 실패하면 자세한 내용을 확인하세요."],
    ConnectionIncompatible => ["未找到所需的控制器服务或特征。确认选择的是 Gear VR 控制器，并检查高级连接配置。", "The required controller service or characteristic was not found. Select a Gear VR controller and check advanced connection settings.", "必要なサービスまたは特性がありません。Gear VR コントローラーを選び、詳細な接続設定を確認してください。", "필요한 서비스 또는 특성이 없습니다. Gear VR 컨트롤러를 선택하고 고급 연결 설정을 확인하세요."],
    ConnectionTimeout => ["连接等待超过 30 秒。检查控制器电量和 Windows 蓝牙状态，重新搜索后再连接。", "Connection timed out after 30 seconds. Check the controller battery and Windows Bluetooth. Search again, then connect.", "接続が 30 秒でタイムアウトしました。電池と Windows の Bluetooth を確認し、再検索して接続してください。", "30초 동안 연결되지 않았습니다. 배터리와 Windows Bluetooth를 확인하고 다시 검색한 후 연결하세요."],
    InputTuning => ["输入调节", "Input", "入力調整", "입력 조정"],
    TestNav => ["输入测试", "Test", "入力テスト", "입력 테스트"],
    General => ["常规", "General", "一般", "일반"],
    Troubleshooting => ["故障排查", "Troubleshoot", "問題の解決", "문제 해결"],
    PendingChanges => ["有未保存的修改。", "Unsaved changes.", "未保存の変更があります。", "저장되지 않은 변경 사항입니다."],
    InputHint => ["保存后用于电脑控制。输入测试使用当前修改值。", "Save changes to use them for desktop control. Tests use your draft values.", "PC 操作には保存後の値を、テストには編集中の値を使います。", "PC 제어에는 저장된 값을 사용합니다. 테스트에는 현재 편집 값을 사용합니다."],
    UnnamedDevice => ["未命名设备", "Unnamed device", "名前のないデバイス", "이름 없는 장치"],
    OtherDevices => ["其他蓝牙设备", "Other Bluetooth devices", "その他の Bluetooth デバイス", "기타 Bluetooth 장치"],
    ServiceMatch => ["匹配控制器服务", "Controller service found", "コントローラーサービスを検出", "컨트롤러 서비스 발견"],
    SeenBefore => ["曾连接", "Previously connected", "接続履歴あり", "이전에 연결됨"],
    NotSeen => ["近期未发现", "Not seen recently", "最近検出されていません", "최근에 발견되지 않음"],
    PublicAddress => ["公共地址", "Public address", "公開アドレス", "공개 주소"],
    RandomAddress => ["随机地址", "Random address", "ランダムアドレス", "임의 주소"],
    UnknownAddress => ["地址类型未知", "Address type unknown", "アドレス種別不明", "주소 유형 알 수 없음"],
    DiscoveryOrder => ["搜索中保持列表位置。结束后按近期可用、连接历史和信号强度排序。信号强度不是距离。", "Rows stay in place while searching. Results then sort by availability, connection history and signal strength. Signal is not distance.", "検索中は位置を維持します。終了後に受信状況、接続履歴、信号強度で並べます。信号は距離ではありません。", "검색 중 위치를 유지합니다. 완료 후 사용 가능 여부, 연결 기록, 신호 세기로 정렬합니다. 신호는 거리가 아닙니다."],
    AppName => ["Gear VR 控制器", "Gear VR Controller", "Gear VR コントローラー", "Gear VR 컨트롤러"],
    Control => ["控制", "Control", "操作", "제어"],
    Tuning => ["调节与校准", "Tune and calibrate", "調整と校正", "조정 및 보정"],
    Settings => ["设置", "Settings", "設定", "설정"],
    HelpNav => ["帮助", "Help", "ヘルプ", "도움말"],
    Help => ["帮助与诊断", "Help and diagnostics", "ヘルプと診断", "도움말 및 진단"],
    ControlHint => ["连接手柄，然后选择控制模式。", "Connect your controller. Then select a mode.", "接続して操作モードを選んでください。", "컨트롤러를 연결한 후 모드를 선택하세요."],
    AddDevice => ["添加控制器", "Add a controller", "コントローラーを追加", "컨트롤러 추가"],
    WakeHint => ["按手柄上的按键唤醒设备。将设备放在电脑附近，然后搜索。", "Press a controller button to wake it. Keep it near your PC. Then search.", "ボタンを押して起動し、PC の近くで検索してください。", "버튼을 눌러 깨운 후 PC 근처에서 검색하세요."],
    Search => ["搜索设备", "Search for devices", "デバイスを検索", "장치 검색"],
    Searching => ["正在搜索。请保持手柄开启。", "Searching. Keep the controller awake.", "検索中です。起動状態を保ってください。", "검색 중입니다. 컨트롤러를 켜 두세요."],
    StopSearch => ["停止搜索", "Stop search", "検索を停止", "검색 중지"],
    NoResults => ["未找到控制器。唤醒手柄后重试，或检查 Windows 配对。", "No controller found. Wake it and try again, or check Windows pairing.", "見つかりません。起動して再検索するか、Windows のペアリングを確認してください。", "장치를 찾지 못했습니다. 다시 검색하거나 Windows 페어링을 확인하세요."],
    Connect => ["连接", "Connect", "接続", "연결"],
    Connecting => ["正在连接", "Connecting", "接続中", "연결 중"],
    CancelConnect => ["取消连接", "Cancel connection", "接続を中止", "연결 취소"],
    Disconnect => ["断开连接", "Disconnect", "切断", "연결 해제"],
    Connected => ["已连接", "Connected", "接続済み", "연결됨"],
    Disconnected => ["未连接控制器", "No controller connected", "未接続", "연결된 컨트롤러 없음"],
    InputPaused => ["输入已暂停", "Input paused", "入力は一時停止中", "입력 일시 중지됨"],
    InputActive => ["正在控制电脑", "Desktop control active", "PC を操作中", "PC 제어 중"],
    Resume => ["开始控制", "Start control", "操作を開始", "제어 시작"],
    Pause => ["暂停输入", "Pause input", "入力を一時停止", "입력 일시 중지"],
    Mode => ["控制模式", "Control mode", "操作モード", "제어 모드"],
    AirMouse => ["空中鼠标", "Air mouse", "エアマウス", "에어 마우스"],
    Touchpad => ["触控板", "Touchpad", "タッチパッド", "터치패드"],
    Presenter => ["演示", "Presenter", "プレゼン", "프레젠테이션"],
    AirHint => ["移动手柄来移动光标。滑动触控板来滚动。", "Move the controller to move the pointer. Swipe the touchpad to scroll.", "本体を動かしてポインターを移動し、パッドをなぞってスクロールします。", "컨트롤러로 포인터를 움직이고 터치패드로 스크롤하세요."],
    TouchHint => ["滑动触控板来移动光标。音量键用于滚动。", "Swipe the touchpad to move the pointer. Use volume buttons to scroll.", "パッドをなぞってポインターを移動し、音量ボタンでスクロールします。", "터치패드로 포인터를 움직이고 음량 버튼으로 스크롤하세요."],
    PresenterHint => ["使用按键和滑动手势控制演示。", "Use buttons and swipe gestures to control slides.", "ボタンとスワイプでスライドを操作します。", "버튼과 스와이프로 슬라이드를 제어하세요."],
    ModeHold => ["长按返回键后松开，可切换模式。", "Hold and release Back to change mode.", "戻るボタンを長押しして離すとモードが変わります。", "뒤로 버튼을 길게 눌렀다 놓으면 모드가 바뀝니다."],
    AutomaticMode => ["模式由前台应用自动选择。手动选择后，本次会话固定该模式。", "The foreground app selected this mode. A manual choice locks it for this session.", "アプリに応じたモードです。手動で選ぶとこのセッション中は固定されます。", "활성 앱이 모드를 선택했습니다. 수동 선택은 이번 세션에 고정됩니다."],
    ManualMode => ["手动选择的模式优先于自动切换。", "Your manual mode takes priority over automatic switching.", "手動選択を自動切替より優先します。", "수동 선택 모드가 자동 전환보다 우선합니다."],
    AdvancedConnection => ["高级连接", "Advanced connection", "詳細な接続", "고급 연결"],
    Address => ["蓝牙地址", "Bluetooth address", "Bluetooth アドレス", "Bluetooth 주소"],
    AddressHint => ["输入 12 位十六进制地址。可包含冒号或短横线。", "Enter 12 hexadecimal digits. Colons and hyphens are allowed.", "16 進数 12 桁を入力します。コロンとハイフンも使用できます。", "16진수 12자리를 입력하세요. 콜론과 하이픈을 사용할 수 있습니다."],
    InvalidAddress => ["地址无效。请输入 12 位十六进制地址。", "Invalid address. Enter 12 hexadecimal digits.", "アドレスが無効です。16 進数 12 桁を入力してください。", "주소가 잘못되었습니다. 16진수 12자리를 입력하세요."],
    LastDevice => ["上次使用的控制器", "Last used controller", "前回のコントローラー", "최근 사용한 컨트롤러"],
    BluetoothSettings => ["打开 Windows 蓝牙设置", "Open Windows Bluetooth settings", "Windows の Bluetooth 設定を開く", "Windows Bluetooth 설정 열기"],
    TuneHint => ["先调节速度，再校准。使用测试区检查结果。", "Adjust speed, then calibrate. Check the result in the test area.", "速度を調整して校正し、テスト領域で確認します。", "속도를 조정하고 보정한 후 테스트 영역에서 확인하세요."],
    AirSpeed => ["空中鼠标速度", "Air mouse speed", "エアマウスの速度", "에어 마우스 속도"],
    TouchSpeed => ["触控板速度", "Touchpad speed", "タッチパッドの速度", "터치패드 속도"],
    NaturalScroll => ["反向滚动", "Reverse scroll direction", "スクロール方向を反転", "스크롤 방향 반전"],
    EdgeMotion => ["触控板边缘持续移动", "Continue moving at the touchpad edge", "パッドの縁で移動を続ける", "터치패드 가장자리에서 계속 이동"],
    EdgeHint => ["关闭时，手指停止后光标也停止。", "When off, the pointer stops when your finger stops.", "オフの場合、指を止めるとポインターも止まります。", "끄면 손가락이 멈출 때 포인터도 멈춥니다."],
    AdvancedInput => ["高级调节", "Advanced tuning", "詳細な調整", "고급 조정"],
    Smoothing => ["平滑移动", "Smooth movement", "移動を滑らかにする", "부드러운 움직임"],
    SmoothingHint => ["减少抖动。较大的值会增加延迟。", "Reduce jitter. Higher values add delay.", "揺れを減らします。値が大きいほど遅延が増えます。", "떨림을 줄입니다. 값이 높으면 지연이 늘어납니다."],
    SmoothingSamples => ["平滑样本数", "Smoothing samples", "平滑化サンプル数", "평활화 샘플 수"],
    DeadZone => ["抖动过滤强度", "Jitter filter strength", "微小動作の除去", "떨림 필터 강도"],
    Acceleration => ["触控板加速", "Touchpad acceleration", "タッチパッドの加速", "터치패드 가속"],
    AccelerationPower => ["加速曲线", "Acceleration curve", "加速曲線", "가속 곡선"],
    Save => ["保存设置", "Save settings", "設定を保存", "설정 저장"],
    Saved => ["设置已保存。", "Settings saved.", "設定を保存しました。", "설정을 저장했습니다."],
    RestoreInput => ["恢复输入默认值", "Restore input defaults", "入力の既定値に戻す", "입력 기본값 복원"],
    Discard => ["放弃修改", "Discard changes", "変更を破棄", "변경 취소"],
    Calibration => ["校准", "Calibration", "校正", "보정"],
    ConnectFirst => ["请先连接控制器，再开始校准或测试。", "Connect the controller before calibration or testing.", "校正やテストの前に接続してください。", "보정이나 테스트 전에 컨트롤러를 연결하세요."],
    GoControl => ["前往控制页", "Go to Control", "操作ページへ", "제어 페이지로 이동"],
    GyroCalibration => ["校准空中鼠标", "Calibrate air mouse", "エアマウスを校正", "에어 마우스 보정"],
    GyroHint => ["把手柄放在桌面上，并保持静止。校准只在本次会话生效。", "Put the controller on a table. Keep it still. Calibration applies to this session.", "机の上に置き、静止させてください。校正は今回のセッションのみ有効です。", "컨트롤러를 탁자에 놓고 움직이지 마세요. 보정은 이번 세션에 적용됩니다."],
    TouchCalibration => ["校准触控板", "Calibrate touchpad", "タッチパッドを校正", "터치패드 보정"],
    TouchCalHint => ["沿触控板边缘移动手指。采集足够数据后保存。", "Trace the touchpad edge. Save when enough data is collected.", "パッドの縁をなぞり、十分なデータが集まったら保存します。", "터치패드 가장자리를 따라 움직이고 데이터가 충분하면 저장하세요."],
    StartGyro => ["开始静止校准", "Start stationary calibration", "静止校正を開始", "정지 보정 시작"],
    StartTouch => ["开始采集边界", "Start edge capture", "縁の記録を開始", "가장자리 수집 시작"],
    SaveCalibration => ["保存校准", "Save calibration", "校正を保存", "보정 저장"],
    Cancel => ["取消", "Cancel", "キャンセル", "취소"],
    CollectingGyro => ["正在采集。保持手柄静止。", "Collecting. Keep the controller still.", "記録中です。静止させてください。", "수집 중입니다. 움직이지 마세요."],
    CollectingTouch => ["正在采集。沿边缘继续移动。", "Collecting. Continue tracing the edge.", "記録中です。縁をなぞり続けてください。", "수집 중입니다. 가장자리를 계속 따라 움직이세요."],
    ReadyToSave => ["采集完成。现在可以保存校准。", "Capture ready. You can save calibration now.", "記録ができました。校正を保存できます。", "수집이 완료되었습니다. 보정을 저장할 수 있습니다."],
    CalibrationDone => ["校准完成。输入保持暂停。测试后再开始控制。", "Calibration complete. Input stays paused. Test before starting control.", "校正完了です。入力は停止中です。テスト後に操作を開始してください。", "보정이 완료되었습니다. 입력은 중지 상태입니다. 테스트 후 제어를 시작하세요."],
    CalibrationCancelled => ["校准已取消。输入保持暂停。", "Calibration cancelled. Input stays paused.", "校正を中止しました。入力は停止中です。", "보정이 취소되었습니다. 입력은 중지 상태입니다."],
    CalibrationMoving => ["手柄发生移动。保持静止后重试。", "The controller moved. Keep it still and try again.", "動きが検出されました。静止させて再試行してください。", "움직임이 감지되었습니다. 정지한 상태로 다시 시도하세요."],
    CalibrationTimeout => ["未及时收到足够数据。检查连接后重试。", "Not enough data arrived in time. Check the connection and try again.", "データが不足しています。接続を確認して再試行してください。", "데이터가 부족합니다. 연결을 확인하고 다시 시도하세요."],
    CalibrationLost => ["连接已断开。重新连接后重试。", "Connection lost. Connect again and retry.", "切断されました。再接続して再試行してください。", "연결이 끊어졌습니다. 다시 연결하고 시도하세요."],
    TestArea => ["输入测试", "Input test", "入力テスト", "입력 테스트"],
    TestHint => ["测试只更新下方读数，不会移动桌面光标或发送按键。", "Testing updates the readings below. It does not move the desktop pointer or send keys.", "下の数値のみ更新します。PC のポインターやキーには送信しません。", "아래 수치만 갱신합니다. PC 포인터를 움직이거나 키를 보내지 않습니다."],
    StartTest => ["开始测试", "Start test", "テストを開始", "테스트 시작"],
    StopTest => ["结束测试", "End test", "テストを終了", "테스트 종료"],
    TestActive => ["测试进行中。桌面输入已暂停。", "Test active. Desktop input is paused.", "テスト中です。PC への入力は停止しています。", "테스트 중입니다. PC 입력은 중지 상태입니다."],
    Clicks => ["点击次数", "Clicks", "クリック数", "클릭 수"],
    Scroll => ["滚动", "Scroll", "スクロール", "스크롤"],
    Bindings => ["按键操作", "Button actions", "ボタンの操作", "버튼 동작"],
    BindingsHint => ["为每种模式选择按键动作。返回键长按仍用于切换模式。", "Choose actions for each mode. Holding Back still changes mode.", "モードごとの動作を選びます。戻るの長押しはモード切替です。", "모드별 동작을 선택하세요. 뒤로 길게 누르기는 모드 전환입니다."],
    Trigger => ["扳机键", "Trigger", "トリガー", "트리거"],
    TouchPress => ["触控板按下", "Touchpad press", "パッドを押す", "터치패드 누르기"],
    Back => ["返回键短按", "Back short press", "戻るの短押し", "뒤로 짧게 누르기"],
    Home => ["主页键", "Home", "ホーム", "홈"],
    LeftClick => ["左键", "Left click", "左クリック", "왼쪽 클릭"],
    RightClick => ["右键", "Right click", "右クリック", "오른쪽 클릭"],
    StartMenu => ["开始菜单", "Start menu", "スタートメニュー", "시작 메뉴"],
    ShowDesktop => ["显示桌面", "Show desktop", "デスクトップを表示", "바탕 화면 표시"],
    PreviousPage => ["上一页", "Previous page", "前のページ", "이전 페이지"],
    NextPage => ["下一页", "Next page", "次のページ", "다음 페이지"],
    PlayPause => ["播放或暂停", "Play or pause", "再生または一時停止", "재생 또는 일시 정지"],
    Disabled => ["不执行动作", "No action", "動作なし", "동작 없음"],
    DuplicateBindings => ["多个按键使用了同一快捷动作。请确认这是你的选择。", "Several buttons use the same shortcut. Check that this is intended.", "同じ操作が複数のボタンに設定されています。意図した設定か確認してください。", "여러 버튼에 같은 동작이 설정되었습니다. 의도한 설정인지 확인하세요."],
    RestoreBindings => ["恢复当前模式的按键", "Restore buttons for this mode", "このモードのボタンを既定値に戻す", "현재 모드 버튼 복원"],
    Background => ["连接与后台", "Connection and background", "接続とバックグラウンド", "연결 및 백그라운드"],
    AutoConnect => ["启动时连接上次设备", "Connect the last device at startup", "起動時に前回のデバイスへ接続", "시작 시 최근 장치 연결"],
    AutoReconnect => ["断线后自动重连", "Reconnect after connection loss", "切断時に再接続", "연결 손실 후 다시 연결"],
    ReconnectHint => ["最多重试 3 次。主动断开后不重连。", "Retry up to 3 times. Do not retry after a manual disconnect.", "最大 3 回試行します。手動で切断した場合は再接続しません。", "최대 3번 시도합니다. 수동 연결 해제 후에는 다시 연결하지 않습니다."],
    Reconnecting => ["正在重新连接。最多尝试 3 次。", "Reconnecting. Up to 3 attempts.", "再接続中です。最大 3 回試行します。", "다시 연결 중입니다. 최대 3번 시도합니다."],
    AutoProfile => ["按前台应用切换模式", "Select mode for the foreground app", "前面アプリに応じてモードを選択", "활성 앱에 맞게 모드 선택"],
    AutoProfileHint => ["手动选择模式后，本次会话不再自动切换。", "A manual mode choice stops automatic switching for this session.", "手動選択後、このセッションの自動切替は停止します。", "수동 선택 후 이번 세션에는 자동 전환하지 않습니다."],
    AntiSleep => ["演示时保持屏幕开启", "Keep the display on during presentation", "プレゼン中は画面を点灯", "프레젠테이션 중 화면 켜 두기"],
    Tray => ["最小化到托盘", "Minimize to tray", "トレイに最小化", "트레이로 최소화"],
    TrayHint => ["最小化后在托盘运行。关闭窗口会退出程序。", "Minimize to run in the tray. Closing the window exits the app.", "最小化するとトレイで動作します。閉じると終了します。", "최소화하면 트레이에서 실행됩니다. 창을 닫으면 앱이 종료됩니다."],
    Language => ["界面语言", "Display language", "表示言語", "표시 언어"],
    SystemLanguage => ["跟随 Windows", "Use Windows language", "Windows の言語を使用", "Windows 언어 사용"],
    HelpHint => ["先检查连接。仅在常规步骤无效时恢复蓝牙服务。", "Check the connection first. Recover the Bluetooth service only if normal steps fail.", "まず接続を確認し、通常の手順で直らない場合のみサービスを再起動します。", "먼저 연결을 확인하세요. 일반 방법이 실패한 경우에만 서비스를 복구하세요."],
    PairingHelp => ["连接失败时，在 Windows 设置中检查配对状态。唤醒手柄后重试。", "If connection fails, check pairing in Windows settings. Wake the controller and retry.", "接続に失敗したら Windows のペアリングを確認し、起動して再試行してください。", "연결에 실패하면 Windows 페어링을 확인하고 컨트롤러를 깨운 후 다시 시도하세요."],
    Recovery => ["恢复蓝牙服务", "Recover Bluetooth service", "Bluetooth サービスを復旧", "Bluetooth 서비스 복구"],
    RecoveryImpact => ["重启服务需要管理员权限，可能中断其他蓝牙设备。请先保存工作。", "Restarting needs administrator permission and can interrupt other Bluetooth devices. Save your work first.", "管理者権限が必要です。他の Bluetooth 機器が切断される場合があります。作業を保存してください。", "관리자 권한이 필요하며 다른 Bluetooth 장치가 끊길 수 있습니다. 작업을 먼저 저장하세요."],
    ConfirmRecovery => ["确认重启蓝牙服务", "Confirm Bluetooth service restart", "サービスの再起動を確認", "Bluetooth 서비스 재시작 확인"],
    RecoveryRunning => ["正在恢复。请等待 Windows 权限提示或操作结果。", "Recovering. Wait for the Windows permission prompt or the result.", "復旧中です。Windows の確認または結果をお待ちください。", "복구 중입니다. Windows 권한 요청이나 결과를 기다리세요."],
    RecoveryDone => ["恢复完成。唤醒手柄，然后重新连接。", "Recovery complete. Wake the controller, then reconnect.", "復旧しました。起動して再接続してください。", "복구되었습니다. 컨트롤러를 깨운 후 다시 연결하세요."],
    OperationFailed => ["操作未完成。请查看诊断详情，再重试。", "The operation did not finish. Check diagnostic details, then retry.", "操作が完了しませんでした。診断の詳細を確認して再試行してください。", "작업이 완료되지 않았습니다. 진단 세부 정보를 확인하고 다시 시도하세요."],
    Details => ["诊断详情", "Diagnostic details", "診断の詳細", "진단 세부 정보"],
    NoDetails => ["没有新的诊断信息。", "No new diagnostic information.", "新しい診断情報はありません。", "새 진단 정보가 없습니다."],
    Sensors => ["传感器数据", "Sensor data", "センサーデータ", "센서 데이터"],
    NoData => ["设备未连接，或尚未收到数据。", "The device is disconnected or no data has arrived.", "未接続、またはデータをまだ受信していません。", "장치가 연결되지 않았거나 데이터가 아직 없습니다."],
    Accel => ["加速度", "Acceleration", "加速度", "가속도"],
    Gyro => ["角速度", "Angular velocity", "角速度", "각속도"],
    Magnet => ["磁场", "Magnetic field", "磁場", "자기장"],
    OpenLogs => ["打开日志文件夹", "Open log folder", "ログフォルダーを開く", "로그 폴더 열기"],
    Export => ["导出诊断摘要", "Export diagnostic summary", "診断概要を出力", "진단 요약 내보내기"],
    ExportHint => ["摘要保存在本机，不含蓝牙地址或原始输入。", "Save the summary locally. It excludes Bluetooth addresses and raw input.", "本機に保存します。Bluetooth アドレスや生入力は含みません。", "이 PC에 저장합니다. Bluetooth 주소나 원시 입력은 포함하지 않습니다."],
    ExportDone => ["诊断摘要已保存。路径见诊断详情。", "Diagnostic summary saved. See diagnostic details for its path.", "診断概要を保存しました。詳細でパスを確認できます。", "진단 요약이 저장되었습니다. 경로는 진단 세부 정보에 있습니다."],
    Open => ["打开", "Open", "開く", "열기"],
    Exit => ["退出", "Exit", "終了", "종료"],
    Pending => ["正在执行，请稍候。", "Working. Please wait.", "処理中です。お待ちください。", "처리 중입니다. 기다려 주세요."],
}
pub fn mode_text(mode: ControlMode) -> Text {
    match mode {
        ControlMode::Mouse => Text::AirMouse,
        ControlMode::Touchpad => Text::Touchpad,
        ControlMode::Presentation => Text::Presenter,
        ControlMode::Settings => Text::Settings,
    }
}
pub fn action_text(action: ButtonAction) -> Text {
    match action {
        ButtonAction::LeftClick => Text::LeftClick,
        ButtonAction::RightClick => Text::RightClick,
        ButtonAction::StartMenu => Text::StartMenu,
        ButtonAction::ShowDesktop => Text::ShowDesktop,
        ButtonAction::PreviousPage => Text::PreviousPage,
        ButtonAction::NextPage => Text::NextPage,
        ButtonAction::PlayPause => Text::PlayPause,
        ButtonAction::Disabled => Text::Disabled,
    }
}
